import { useState } from "react";
import { Check, Film, Plus, X } from "lucide-react";
import { segmentSeed } from "./fixtures";
import type { PreviewCase } from "./fixtures";

export function EpisodeSample({ scenario, studio, onOpen, onBack }: { scenario: PreviewCase; studio: boolean; onOpen: () => void; onBack: () => void }) {
  const [segments, setSegments] = useState(scenario === "empty" ? [] : segmentSeed(scenario === "45"));
  const [active, setActive] = useState(1);
  const [notice, setNotice] = useState("");
  const [showAI, setShowAI] = useState(false);
  const [showExport, setShowExport] = useState(false);
  const [reference, setReference] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [failed, setFailed] = useState(false);
  const [assembled, setAssembled] = useState(false);
  const [request, setRequest] = useState<{ id: number; text: string; seconds: number } | null>(null);
  const current = segments.find(s => s.id === active) ?? segments[0];
  const total = segments.reduce((n, s) => n + s.seconds, 0);
  const updateText = (text: string) => { setSegments(items => items.map(s => s.id === current?.id ? { ...s, text, stale: s.adopted > 0 } : s)); setAssembled(false); };
  const add = () => { const id = Math.max(0, ...segments.map(s => s.id)) + 1; setSegments([...segments, { id, seconds: 7, text: "", candidate: 0, adopted: 0, stale: false }]); setActive(id); setAssembled(false); };
  const ai = () => { onOpen(); setShowAI(true); };
  const body = <><header className="r0v-heading"><div><small className="r0v-eyebrow">EPISODE VIDEOS</small><h1>分集视频</h1><p>剧本正文与片段脚本是不同对象 · 独立页面内容样稿</p></div></header><div className="r0v-episode-grid">{[1, 2].map(id => <article className="r0v-episode-card" key={id}><div className="r0v-episode-cover"><Film size={32}/><span>EP 0{id}</span></div><div><span className="r0v-tag">{id === 1 && segments.length ? "片段脚本就绪（样例）" : "待生成片段脚本"}</span><h2>第{id}集 · {id === 1 ? "冷宫第一炉" : "一饼一笔账"}</h2><p>{id === 1 ? `${segments.length} 个片段 · ${total} 秒` : "尚无片段脚本 · 可手写或AI生成"}</p><div className="r0v-actions"><button onClick={() => { if (id === 2) { setSegments([]); setActive(1); } onOpen(); }}>编辑脚本</button><button className="r0v-primary" onClick={() => { if (id === 2) setSegments([]); ai(); }}>AI生成脚本</button></div></div></article>)}</div></>;
  if (!studio) return body;
  return <><header className="r0v-heading"><div><small className="r0v-eyebrow">SEGMENT SCRIPT</small><h1>片段脚本</h1><p>{segments.length} 个片段 · 合计 {total} 秒 · 本地交互样稿</p></div><div className="r0v-actions"><button onClick={onBack}>返回分集列表</button><button onClick={() => setShowExport(!showExport)}>导出方案</button><button className="r0v-primary" disabled={!segments.length || segments.some(s => !s.adopted || s.stale) || scenario === "stale"} onClick={() => { setAssembled(true); setNotice("整集合成状态示意，未生成视频文件。"); }}>模拟合成整集</button></div></header>
    {scenario === "stale" && <div className="r0v-warning">正文版本变化：原有定稿规则仍保留，编辑脚本不会跳过正式确认。</div>}
    {showExport && <section className="r0v-callout"><span>计划支持：MP4、通用素材包、PR可导入XML、指定版本剪映草稿。R0不生成实际文件，外部软件兼容尚未验收。</span><button aria-label="关闭导出方案" onClick={() => setShowExport(false)}><X size={16}/></button></section>}
    <div className="r0v-studio"><aside className="r0v-panel"><h3>本集素材</h3><p className="r0v-muted">引用是结构化关系，不仅是文字。</p>{["沈知微 · 常服", "苏嬷嬷", "小厨房 · 清晨", "旧粮袋", "沈知微 · 声线"].map(name => <div className="r0v-material" key={name}><span>{name}</span><small>{scenario === "missing" && name.startsWith("小厨房") ? "待补素材" : "样例引用"}</small></div>)}<button disabled={!current} onClick={() => setReference(!reference)}>{reference ? "移除本段引用（模拟）" : "绑定本段素材（模拟）"}</button></aside>
      <section className="r0v-panel r0v-script-editor"><div className="r0v-row"><h2>{current ? `片段 ${String(current.id).padStart(2, "0")}` : "暂无片段"}</h2><button onClick={ai}>AI生成脚本</button></div>
        {showAI && <div className="r0v-callout"><span>只补空白脚本，保留已编辑内容。模拟AI，不调用模型。</span><button className="r0v-primary" onClick={() => { const seed = segmentSeed(scenario === "45"); setSegments(items => items.length ? items.map((s, i) => s.text.trim() ? s : { ...s, text: seed[i % seed.length]!.text }) : seed); setShowAI(false); setNotice("已填入模拟脚本；未调用模型。"); }}>模拟补全空白</button><button onClick={() => setShowAI(false)}>取消</button></div>}
        {current ? <><div className="r0v-tags">{reference ? <><span>@沈知微 · 常服</span><span>@小厨房 · 清晨</span><span>@旧粮袋</span></> : <span>未绑定素材 · 仍可编辑</span>}</div><label className="r0v-duration">本段时长（秒）<input type="number" min="1" max="120" value={current.seconds} onChange={e => { const value = Number(e.target.value); if (value >= 1 && value <= 120) { setSegments(items => items.map(s => s.id === current.id ? { ...s, seconds: value, stale: s.adopted > 0 } : s)); setAssembled(false); } }}/></label><textarea aria-label="片段脚本内容" value={current.text} onChange={e => updateText(e.target.value)}/><div className="r0v-row"><button onClick={() => setNotice("脚本已暂存本次会话；未修改剧本正文，刷新后重置。")}>保存脚本</button><span className="r0v-muted">{current.stale ? "脚本修改，采用视频需复核" : "独立片段脚本"}</span></div></> : <div className="r0v-empty"><Film size={30}/><h3>先写一个片段</h3><p>可手动新增，也可模拟AI规划。</p><button onClick={add}>新增片段</button></div>}
      </section>
      <aside className="r0v-panel"><h3>片段预览</h3><div className="r0v-video-placeholder"><Film size={42}/><p>{assembled ? "整集预览占位" : current?.candidate ? `候选 V${current.candidate} · 预览占位` : "尚无视频候选"}</p><small>没有实际视频文件</small></div><button className="r0v-primary" disabled={!current?.text.trim() || !reference || scenario === "missing" || scenario === "stale" || generating} onClick={() => { setGenerating(true); setFailed(false); setRequest({ id: current!.id, text: current!.text, seconds: current!.seconds }); }}>模拟生成视频</button>{(scenario === "missing" || !reference) && <p className="r0v-attention">缺少必需素材，脚本仍可编辑。</p>}{generating && <div className="r0v-stack"><p role="status">模拟生成中</p><button onClick={() => { setGenerating(false); setNotice("模拟任务已取消，候选未变化。"); }}>取消视频任务</button><button onClick={() => { setGenerating(false); if (scenario === "failed") { setFailed(true); } else { setSegments(items => items.map(s => s.id === request?.id ? { ...s, candidate: s.candidate + 1, candidateText: request.text, candidateSeconds: request.seconds } : s)); } }}>模拟供应商返回</button></div>}{failed && <p className="r0v-error">模拟失败：媒体下载失败。可再次点击模拟生成视频。</p>}{Boolean(current?.candidate) && <button onClick={() => { setSegments(items => items.map(s => s.id === current?.id ? { ...s, adopted: s.candidate, stale: s.candidateText !== s.text || s.candidateSeconds !== s.seconds } : s)); setAssembled(false); }}><Check size={14}/>{current?.adopted === current?.candidate ? "当前候选已采用" : "采用当前候选"}</button>}</aside>
    </div><section className="r0v-segment-strip" aria-label="片段列表">{segments.map(s => <button key={s.id} aria-pressed={s.id === current?.id} onClick={() => setActive(s.id)}><Film size={20}/><strong>片段 {String(s.id).padStart(2, "0")}</strong><small>{s.seconds} 秒 · {s.stale ? "需复核" : s.adopted ? "已采用" : "待视频"}</small></button>)}<button onClick={add}><Plus size={20}/>新增片段</button></section><p role="status" className="r0v-muted">{notice || "片段单选 · 一段一个视频单元 · 不提供多选、智能预演或多轨编辑器"}</p></>;
}
