import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Check, ChevronRight, PanelLeftClose, PanelLeftOpen, ShieldCheck, Sparkles, X } from "lucide-react";
import { Button, Dialog } from "@/components/ui";
import "@/styles/script-review-preview.css";

const titles = ["冷宫第一炉", "一饼一笔账", "半碗粮的分量", "封门后的席", "把粮还给人", "旧案开封", "一味旧证"];
const findings = [
  { title: "监管内侍的姓名发生变化", scope: "EP 06 → EP 07", episode: 6, level: "冲突", before: "新任监管内侍刘喜奉命前来。", after: "李公公既来验收，正好。", suggestion: "将本集称呼统一为“刘公公”，保留验收情节。" },
  { title: "冷宫人数缺少过渡说明", scope: "EP 01 → EP 05", episode: 4, level: "冲突", before: "苏嬷嬷：冷宫十二人。", after: "阿禾：今日第一批，冷宫三十七人，份量全齐。", suggestion: "明确这批供膳还包括其他宫院，不改变既有冷宫人数。" },
  { title: "旧御膳房钥匙尚未承接", scope: "EP 05 → EP 06", episode: 5, level: "提醒", before: "沈知微：明日去取。", after: "旧案重新开封，众人开始核对档案。", suggestion: "补上一句取档经过，或说明计划暂缓的原因。" },
];
const initialScripts = titles.map((title, index) => `【第${index + 1}集 · ${title}】\n\n【场景一  冷宫偏院·清晨】\n【人物】沈知微、苏嬷嬷、阿禾、监管内侍\n\n晨雾贴着残墙缓缓散开。灶房门外，阿禾将一碗热粥放在旧木桌上，手里紧紧攥着昨日留下的粮单。\n\n阿禾：\n娘娘，昨日的账，我又核了一遍。\n\n沈知微没有急着接话。她摊开旧粮单，将折角压平，指尖停在被涂改的仓号上。\n\n沈知微：\n先看东西从哪里来，再问是谁签的字。\n\n苏嬷嬷走到门边，望见一道深色身影穿过院门。来人停在桌前，将验收牌放下。\n\n${index === 6 ? "沈知微：\n李公公既来验收，正好。" : "苏嬷嬷：\n新任监管内侍刘喜奉命前来。"}\n\n她把粮单推向桌子中央，没有松开压住纸角的手。\n\n【场景二  灶房·片刻后】\n\n锅里热气渐起。阿禾从柜底取出旧铜钥匙，和粮单并排放在桌上。\n\n沈知微：\n这一次，我们把来龙去脉记清楚。`);

export default function ScriptReviewPreviewPage() {
  const [episode, setEpisode] = useState(6);
  const [collapsed, setCollapsed] = useState(false);
  const [drawer, setDrawer] = useState(false);
  const [issue, setIssue] = useState<number | null>(0);
  const [proposal, setProposal] = useState(false);
  const [keeping, setKeeping] = useState(false);
  const [reason, setReason] = useState("");
  const [resolved, setResolved] = useState<Record<number, string>>({});
  const [scripts, setScripts] = useState(initialScripts);
  const [editing, setEditing] = useState(false);
  const [finalizing, setFinalizing] = useState(false);
  const [durations, setDurations] = useState(titles.map(() => 60));
  const [acknowledged, setAcknowledged] = useState(false);
  const [notice, setNotice] = useState("");
  const remaining = findings.filter((_, index) => !resolved[index]).length;
  const current = issue === null ? null : findings[issue];
  const choose = (index: number) => { const finding = findings[index]; if (!finding) return; setIssue(issue === index ? null : index); setEpisode(finding.episode); setProposal(false); setKeeping(false); setReason(""); };
  const finishIssue = (label: string) => { if (issue !== null) setResolved(value => ({ ...value, [issue]: label })); setProposal(false); setKeeping(false); };
  return <div className={`srp ${collapsed ? "srp--collapsed" : ""} ${drawer ? "srp--reviewing" : ""}`}>
    <header className="srp-header"><Link to="/projects"><ArrowLeft size={17} /> 返回项目</Link><strong>冷宫食肆</strong><span className="srp-demo">交互测试页 · 示例数据，不保存到项目</span><div className="srp-topsteps"><b>1. 剧本创作</b><span>2. 资产库</span><span>3. 分集视频</span></div></header>
    <aside className="srp-rail"><header><strong>{collapsed ? "流程" : "从素材到制作准备"}</strong><Button variant="text" controlSize="compact" aria-label={collapsed ? "展开菜单" : "收起菜单"} icon={collapsed ? <PanelLeftOpen size={17} /> : <PanelLeftClose size={17} />} onClick={() => setCollapsed(!collapsed)} /></header><div className="srp-stages">{["故事策划", "分集大纲", "剧本正文", "制作准备"].map((stage, index) => <div key={stage} className={index === 2 ? "active" : ""}><span>{index < 2 ? "✓" : index + 1}</span>{!collapsed && <strong>{stage}</strong>}</div>)}</div><h3>{collapsed ? "集数" : "剧集目录 · 7"}</h3><nav aria-label="剧集目录">{titles.map((title, index) => <button key={title} aria-current={episode === index ? "page" : undefined} onClick={() => { setEpisode(index); setEditing(false); }}><span>EP {String(index + 1).padStart(2, "0")}</span>{!collapsed && <div><strong>{title}</strong><small>60 秒 · 待定稿</small></div>}</button>)}</nav></aside>
    <main className="srp-main"><div className="srp-heading"><div><small>SCREENPLAY WORKSPACE</small><h1>剧本正文</h1><p>让故事连贯发生，把决定留给创作者。</p></div><span>7 集 · 正文已齐全</span></div>
      <div className="srp-status"><ShieldCheck size={21} /><div><strong>{remaining ? `${remaining} 项待审阅` : "本轮问题已处理"}</strong><span>{remaining ? "校对建议已就绪，点击问题可对照原文处理。" : "可以继续阅读，或进行全集定稿。"}</span></div><Button variant={remaining ? "danger" : "secondary"} onClick={() => setDrawer(!drawer)}>{drawer ? "收起校对" : "查看并处理"}<ChevronRight size={15} /></Button></div>
      {notice && <div className="srp-notice" role="status">{notice}<Button variant="text" controlSize="compact" aria-label="关闭提示" icon={<X size={14} />} onClick={() => setNotice("")} /></div>}
<article className="srp-paper"><header><small>SCREENPLAY / EP {String(episode + 1).padStart(2, "0")}</small><span>V1 · 示例版本</span></header><h2>{titles[episode]}</h2><p className="srp-synopsis">沈知微从一张旧粮单中发现仓号被人涂改。她与苏嬷嬷重新核对来路，在验收之前留下实物与记录，让旧案有了可以追查的线索。</p>{editing ? <textarea aria-label="编辑本集正文" value={scripts[episode]} onChange={event => { const text = event.target.value; setScripts(value => value.map((script, index) => index === episode ? text : script)); }} /> : <div className="srp-script">{scripts[episode]}</div>}<footer><span>{(scripts[episode] ?? "").length} 字 · 预计 {durations[episode]} 秒</span><Button onClick={() => { setEditing(!editing); if (editing) { setResolved({}); setNotice("示例正文已更新，相关校对结论需要复查。"); } }}>{editing ? "完成编辑" : "编辑正文"}</Button></footer></article>
      <footer className="srp-finalbar"><div><strong>准备好进入下一步了吗？</strong><span>定稿时核对集数、时长与审阅结果。</span></div><Button variant="primary" onClick={() => { setFinalizing(true); setAcknowledged(false); }}>确认定稿，进入制作准备</Button></footer>
    </main>
    {drawer && <aside className="srp-drawer" aria-label="剧本校对"><header><div><small>SCRIPT REVIEW</small><h2>剧本校对 <span>{remaining}</span></h2></div><Button variant="text" aria-label="关闭校对" icon={<X size={18} />} onClick={() => setDrawer(false)} /></header><p className="srp-drawer-intro">逐条核对，按你的创作意图决定。选择问题会定位到对应分集。</p><div className="srp-issues">{findings.map((finding, index) => <section key={finding.title} className={issue === index ? "selected" : ""}><button className="srp-issue-title" aria-expanded={issue === index} onClick={() => choose(index)}><span className={`srp-severity ${resolved[index] ? "done" : ""}`}>{resolved[index] ? "已审阅" : finding.level}</span><strong>{finding.title}</strong><small>{finding.scope}</small><ChevronRight size={15} /></button>{issue === index && <div className="srp-evidence"><label>前集依据</label><blockquote>{finding.before}</blockquote><label>本集内容</label><blockquote>{finding.after}</blockquote><p>{finding.suggestion}</p>{resolved[index] ? <p className="srp-resolution"><Check size={15} />{resolved[index]}</p> : <div className="srp-issue-actions"><Button onClick={() => { setEditing(true); setNotice(`已打开第 ${finding.episode + 1} 集编辑，可在正文中修改。`); }}>手动修改</Button><Button variant="primary" icon={<Sparkles size={14} />} onClick={() => setProposal(true)}>预览 AI 修订</Button><Button variant="text" onClick={() => setKeeping(true)}>保留原文并说明</Button></div>}{keeping && <div className="srp-keep"><label htmlFor="srp-reason">保留理由</label><textarea id="srp-reason" placeholder="例如：这是刻意安排的伏笔，后续会交代。" value={reason} onChange={event => setReason(event.target.value)} /><Button disabled={!reason.trim()} onClick={() => finishIssue(`人工保留：${reason.trim()}`)}>确认保留</Button></div>}</div>}</section>)}</div><footer><span>示例校对 · 不调用模型</span><Button onClick={() => { setNotice("测试页已演示重新检查：未处理的问题继续保留，正式版将调用模型检查最新正文。"); }}>重新检查</Button></footer></aside>}
    <Dialog open={proposal} size="large" title={`第 ${(current?.episode ?? 0) + 1} 集 · 局部修订对比`} description="演示提案：确认后仅更新本测试页。" onClose={() => setProposal(false)} footer={<><Button onClick={() => setProposal(false)}>返回校对</Button><Button variant="primary" onClick={() => { if (current) setScripts(value => value.map((text, index) => index === current.episode ? text.replaceAll("李公公", "刘公公") + `\n\n【修订说明】${current.suggestion}` : text)); finishIssue("已应用示例修订 · 待复查"); setNotice("示例修订已应用；正式版在应用后会要求复查受影响的正文。"); }}>应用到测试稿</Button></>}><div className="srp-compare"><section><h3>修改前</h3><p>{current?.after}</p></section><section><h3>修改后</h3><p>{issue === 0 ? "刘公公既来验收，正好。" : current?.suggestion}</p></section></div><p>修改范围：本集相关台词与交接说明。其余段落保持原样。</p></Dialog>
    <Dialog open={finalizing} size="large" title="全集定稿" description="核对这一版剧本，将它作为下一阶段的制作依据。" onClose={() => setFinalizing(false)} footer={<><Button onClick={() => setFinalizing(false)}>继续编辑</Button><Button variant="primary" disabled={!acknowledged || durations.some(value => !Number.isFinite(value) || value < 1 || value > 3600)} onClick={() => { setFinalizing(false); setNotice("测试定稿成功：已演示进入制作准备。真实项目与正文未修改。"); }}>确认本版剧本</Button></>}><div className="srp-final-summary"><strong>7 / 7 集正文完整</strong><span>总时长 {durations.reduce((sum, value) => sum + value, 0)} 秒</span></div><div className="srp-final-review"><span>{remaining ? `${remaining} 项校对建议待审阅，可人工复核后定稿。` : "本轮建议已处理，仍请核对最终正文。"}</span><Button variant="text" onClick={() => { setFinalizing(false); setDrawer(true); }}>返回校对</Button></div><div className="srp-duration-head"><strong>每集目标时长</strong><Button controlSize="compact" onClick={() => setDurations(titles.map(() => 60))}>统一设为 60 秒</Button></div><div className="srp-durations">{titles.map((title, index) => <label key={title}><span><small>EP {String(index + 1).padStart(2, "0")}</small> {title}</span><div><input type="number" aria-label={`第 ${index + 1} 集时长`} min={1} max={3600} value={durations[index]} onChange={event => { const value = Number(event.target.value); setDurations(values => values.map((duration, i) => i === index ? value : duration)); }} />秒</div></label>)}</div><label className="srp-ack"><input type="checkbox" checked={acknowledged} onChange={event => setAcknowledged(event.target.checked)} />我已人工核对当前版本，并接受保留的创作安排。</label></Dialog>
  </div>;
}
