"""ORM 模型集合。

Alembic autogenerate 依赖此处的导入来发现全部模型，新增模型必须在这里登记。
"""

from app.models.edit_project import EditProject, EditProjectReceipt  # noqa: F401
from app.models.agent_config import (
    AGENT_MODES,
    MEDIA_MODALITIES,
    AgentSkill,
    AgentSkillVersion,
    BusinessExecutorSetting,
    StylePreset,
)
from app.models.asset import (
    ASSET_TYPE_CANVAS,
    ASSET_TYPE_CHARACTER,
    ASSET_TYPE_COSTUME,
    ASSET_TYPE_PROP,
    ASSET_TYPE_REFERENCE,
    ASSET_TYPE_SCENE,
    ASSET_TYPE_VIDEO,
    ASSET_TYPE_VOICE,
    ASSET_TYPES,
    Asset,
    AssetUsage,
    AssetVersion,
    MediaFile,
    ProjectAssetLink,
    ProjectMediaLink,
)
from app.models.base import IdMixin, TimestampMixin, utcnow
from app.models.production_contract import AssetProductionReceipt, SegmentScriptSnapshot  # noqa: F401
from app.models.episode_edit import EpisodeEditDraft, EpisodeEditReceipt  # noqa: F401
from app.models.billing import BillingCall, BillingReceipt
from app.models.canvas import CanvasDocument, CanvasEdge, CanvasNode
from app.models.canvas_agent import CanvasAgentMessage, CanvasAgentThread
from app.models.continuity import (
    CONTINUITY_CONFIRMATION_CONFIRMED,
    CONTINUITY_CONFIRMATION_DRAFT,
    CONTINUITY_STATUS_ACTIVE,
    CONTINUITY_STATUS_SUPERSEDED,
    StoryContinuityFact,
)
from app.models.creation import (
    ARTIFACT_STATUS_CONFIRMED,
    ARTIFACT_STATUS_DRAFT,
    ARTIFACT_STATUS_SUPERSEDED,
    ARTIFACT_TYPE_EPISODE_OUTLINE,
    ARTIFACT_TYPE_EPISODE_SCRIPT,
    ARTIFACT_TYPE_SCENE_SHOT_DRAFT,
    ARTIFACT_TYPE_STORY_BIBLE,
    JOB_TARGET_OUTLINE_AGENT,
    SESSION_STATUS_BREAKDOWN_COMPLETED,
    SESSION_STATUS_BREAKDOWN_GENERATING,
    SESSION_STATUS_BREAKDOWN_REVIEWING,
    SESSION_STATUS_COMPLETED,
    SESSION_STATUS_CONFIRMED,
    SESSION_STATUS_DRAFT,
    SESSION_STATUS_GENERATING,
    SESSION_STATUS_OUTLINE_CONFIRMED,
    SESSION_STATUS_OUTLINE_GENERATING,
    SESSION_STATUS_OUTLINE_REVIEWING,
    SESSION_STATUS_REVIEWING,
    SESSION_STATUS_SCRIPT_GENERATING,
    SESSION_STATUS_SCRIPT_REVIEWING,
    CreationArtifact,
    CreationMessage,
    CreationSession,
)
from app.models.job import (
    JOB_STATUS_CANCELLED,
    JOB_STATUS_DOWNLOADING,
    JOB_STATUS_FAILED,
    JOB_STATUS_PROCESSING,
    JOB_STATUS_QUEUED,
    JOB_STATUS_RETRYING,
    JOB_STATUS_RUNNING,
    JOB_STATUS_SUCCEEDED,
    JOB_TYPE_EXPORT,
    JOB_TYPE_IMAGE,
    JOB_TYPE_SCRIPT,
    JOB_TYPE_STORYBOARD,
    JOB_TYPE_TEXT,
    JOB_TYPE_TTS,
    JOB_TYPE_VIDEO,
    Job,
)
from app.models.job_text_response import JobTextResponse
from app.models.execution_policy import ExecutionPolicy
from app.models.market_research import MarketIdeaProject, MarketResearchRun
from app.models.project import (
    PROJECT_STATUS_ACTIVE,
    PROJECT_STATUS_ARCHIVED,
    PROJECT_STATUS_DRAFT,
    SHOT_STATUS_FAILED,
    SHOT_STATUS_GENERATING,
    SHOT_STATUS_PENDING,
    SHOT_STATUS_READY,
    Episode,
    EpisodeProduction,
    EpisodeProductionPlan,
    Project,
    Scene,
    SegmentVideoVersion,
    Shot,
    ShotVideoVersion,
    VideoSegment,
    VideoSegmentShot,
)
from app.models.provider import (
    MODEL_TYPE_AUDIO,
    MODEL_TYPE_EMBEDDING,
    MODEL_TYPE_IMAGE,
    MODEL_TYPE_TEXT,
    MODEL_TYPE_TTS,
    MODEL_TYPE_VIDEO,
    MODEL_TYPES,
    PROTOCOL_FAKE_VIDEO,
    PROTOCOL_GOOGLE_GEMINI,
    PROTOCOL_OPENAI_COMPATIBLE,
    PROVIDER_PROTOCOLS,
    AISettings,
    Provider,
    ProviderModel,
)
from app.models.script_import import (
    IMPORT_STATUS_CONFIRMED,
    IMPORT_STATUS_CONFIRMING,
    IMPORT_STATUS_DRAFT,
    MATERIAL_TYPE_FULL_SCRIPT,
    MATERIAL_TYPE_STORY_OUTLINE,
    MATERIAL_TYPE_UNKNOWN,
    ScriptImportSession,
)
from app.models.script_version import ScriptVersion
from app.models.user import ROLE_ADMIN, ROLE_MEMBER, User
from app.models.worker_runtime import WorkerRuntime

from app.models.audit import AuditEvent as AuditEvent
from app.models import team_ownership as team_ownership  # register ownership rule

__all__ = [
    "StoryContinuityFact",
    "CONTINUITY_CONFIRMATION_CONFIRMED",
    "CONTINUITY_CONFIRMATION_DRAFT",
    "CONTINUITY_STATUS_ACTIVE",
    "CONTINUITY_STATUS_SUPERSEDED",
    "WorkerRuntime",
    "BillingCall",
    "BillingReceipt",
    "ARTIFACT_STATUS_CONFIRMED",
    "ARTIFACT_STATUS_DRAFT",
    "ARTIFACT_STATUS_SUPERSEDED",
    "ARTIFACT_TYPE_EPISODE_OUTLINE",
    "ARTIFACT_TYPE_EPISODE_SCRIPT",
    "ARTIFACT_TYPE_SCENE_SHOT_DRAFT",
    "ARTIFACT_TYPE_STORY_BIBLE",
    "AGENT_MODES",
    "MEDIA_MODALITIES",
    "JOB_TARGET_OUTLINE_AGENT",
    "ASSET_TYPES",
    "ASSET_TYPE_CHARACTER",
    "ASSET_TYPE_COSTUME",
    "ASSET_TYPE_PROP",
    "ASSET_TYPE_REFERENCE",
    "ASSET_TYPE_SCENE",
    "ASSET_TYPE_VOICE",
    "ASSET_TYPE_VIDEO",
    "ASSET_TYPE_CANVAS",
    "JOB_STATUS_CANCELLED",
    "JOB_STATUS_DOWNLOADING",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_PROCESSING",
    "JOB_STATUS_QUEUED",
    "JOB_STATUS_RETRYING",
    "JOB_STATUS_RUNNING",
    "JOB_STATUS_SUCCEEDED",
    "JOB_TYPE_EXPORT",
    "JOB_TYPE_IMAGE",
    "JOB_TYPE_SCRIPT",
    "JOB_TYPE_STORYBOARD",
    "JOB_TYPE_TEXT",
    "JOB_TYPE_TTS",
    "JOB_TYPE_VIDEO",
    "MODEL_TYPES",
    "MODEL_TYPE_AUDIO",
    "MODEL_TYPE_EMBEDDING",
    "MODEL_TYPE_IMAGE",
    "MODEL_TYPE_TEXT",
    "MODEL_TYPE_TTS",
    "MODEL_TYPE_VIDEO",
    "PROJECT_STATUS_ACTIVE",
    "PROJECT_STATUS_ARCHIVED",
    "PROJECT_STATUS_DRAFT",
    "PROTOCOL_OPENAI_COMPATIBLE",
    "PROTOCOL_GOOGLE_GEMINI",
    "PROTOCOL_FAKE_VIDEO",
    "PROVIDER_PROTOCOLS",
    "AISettings",
    "ROLE_ADMIN",
    "ROLE_MEMBER",
    "SESSION_STATUS_BREAKDOWN_COMPLETED",
    "SESSION_STATUS_BREAKDOWN_GENERATING",
    "SESSION_STATUS_BREAKDOWN_REVIEWING",
    "SESSION_STATUS_COMPLETED",
    "SESSION_STATUS_CONFIRMED",
    "SESSION_STATUS_DRAFT",
    "SESSION_STATUS_GENERATING",
    "SESSION_STATUS_OUTLINE_CONFIRMED",
    "SESSION_STATUS_OUTLINE_GENERATING",
    "SESSION_STATUS_OUTLINE_REVIEWING",
    "SESSION_STATUS_REVIEWING",
    "SESSION_STATUS_SCRIPT_GENERATING",
    "SESSION_STATUS_SCRIPT_REVIEWING",
    "SHOT_STATUS_FAILED",
    "SHOT_STATUS_GENERATING",
    "SHOT_STATUS_PENDING",
    "SHOT_STATUS_READY",
    "Asset",
    "AgentSkill",
    "AgentSkillVersion",
    "BusinessExecutorSetting",
    "AssetUsage",
    "AssetVersion",
    "CanvasDocument",
    "CanvasAgentMessage",
    "CanvasAgentThread",
    "CanvasEdge",
    "CanvasNode",
    "CreationArtifact",
    "CreationMessage",
    "CreationSession",
    "Episode",
    "EpisodeProduction",
    "EpisodeProductionPlan",
    "IdMixin",
    "Job",
    "JobTextResponse",
    "ExecutionPolicy",
    "EditProject",
    "MediaFile",
    "MarketResearchRun",
    "MarketIdeaProject",
    "ProjectAssetLink",
    "ProjectMediaLink",
    "Project",
    "Provider",
    "ProviderModel",
    "Scene",
    "ScriptVersion",
    "ScriptImportSession",
    "IMPORT_STATUS_DRAFT",
    "IMPORT_STATUS_CONFIRMING",
    "IMPORT_STATUS_CONFIRMED",
    "MATERIAL_TYPE_UNKNOWN",
    "MATERIAL_TYPE_STORY_OUTLINE",
    "MATERIAL_TYPE_FULL_SCRIPT",
    "StylePreset",
    "Shot",
    "ShotVideoVersion",
    "SegmentVideoVersion",
    "VideoSegment",
    "VideoSegmentShot",
    "TimestampMixin",
    "User",
    "Workspace",
    "WorkspaceMembership",
    "WorkspaceInvitation",
    "utcnow",
]

from app.models.workspace import Workspace, WorkspaceMembership, WorkspaceInvitation
from app.models.auth_session import BrowserSession, LoginRateLimit  # noqa: F401
from app.models.object_storage import UserObjectStorage, ObjectStorageVersion  # noqa: F401
from app.core import workspace_orm  # noqa: F401
from app.models.media_reservation import MediaReservation  # noqa: F401
from app.models.storage_cleanup import MediaCleanup
from app.core import media_quota  # noqa: F401
from app.models.episode_planning import EpisodePlanningRecord, PlanningResponseRecord  # noqa: F401
